name: NeonBan
main: top.efish.neonban.NeonBan
version: 0.1
commands:
  neonban:
    description: NeonBan commands
    usage: /<command> <update|list|version|report>
permissions:
  neonban.update:
    description: Allows the user to update the ban list
    default: op
  neonban.list:
    description: Allows the user to list banned players
    default: op
  neonban.version:
    description: Allow the user check the plugin version
    default: op
  neonban.report:
    description: Allows the user to receive the report link
    default: not op